### ISSUE TITLE
map: T0:  plot bug? test again qa.restricted.

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-eda#18]
https://aurreco-n.clinepidb.org/ce.aurreco-n/app/workspace/maps/rRSLpK1/import

```
2024-04-21 13:48:34.556 [rid:2ZaFx][jid:][p:] DEBUG PrometheusFilter:165 - Request end: POST /merging-internal/query 200
2024-04-21 13:48:34.557 [rid:     ][jid:][p:] ERROR ErrorMapper:68 - Caught Exception: 
 org.veupathdb.service.eda.common.client.NonEmptyResultStream$EmptyResultException: Requested data stream '5856ef3f-9468-4639-b055-ed64da2c393f' did not contain any data.
	at org.veupathdb.service.eda.common.client.NonEmptyResultStream.throwException(NonEmptyResultStream.java:81) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.common.client.NonEmptyResultStream.<init>(NonEmptyResultStream.java:38) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildDataStreams(StreamingDataClient.java:72) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.common.client.StreamingDataClient.buildAndProcessStreams(StreamingDataClient.java:38) ~[service.jar:3.0.0]
	at org.veupathdb.service.eda.merge.core.MergeRequestProcessor.lambda$createMergedResponseSupplier$4(MergeRequestProcessor.java:89) ~[service.jar:3.0.0]
```

<img width="1319" alt="Screenshot 2024-04-21 at 1 51 56 PM" src="https://github.com/VEuPathDB/service-eda/assets/16354313/9d24a19f-5000-4aaa-9f6d-8e6dfc3d2f22">

**Comment by aurreco-uga** [comment]
seems to be working
